import pandas as pd
from matplotlib import pyplot as plt
import os

data=pd.read_csv("D:/Users/Polina/studing/курсовая_магистратура/весна 2019/график 5 КБ predictors.txt", sep="\t")
print(data.keys())
print(data)
fig = plt.figure()
ax1 = fig.add_subplot(111)
data.sort_values(by="model_number", inplace=True)
chr4_scc = list(data["chr4"])
chr10_scc = list(data["chr10"])
chr15_scc = list(data["chr15"])
name = list(data["model_2"])
ax1.scatter(range(len(chr4_scc)), chr4_scc, s=20, c='b', marker="o", label='chr4')
ax1.scatter(range(len(chr10_scc)),chr10_scc, s=20, c='r', marker="o", label='chr10')
ax1.scatter(range(len(chr4_scc)),chr15_scc, s=20, c='g', marker="o", label='chr15')
plt.setp(plt.gca().get_xticklabels(), rotation=45, fontsize=7)
plt.grid(True)
# plt.scatter(data['contact_count'], pe_prediction["0"])
# plt.ylabel("SCC", fontsize=16)
# plt.xlabel("model", fontsize=16)
plt.xticks(range(len(chr4_scc)),name)
# print(name[10],f[10])
plt.legend(loc='upper left')
plt.show()